### ISSUE TITLE
DNS issue

### ISSUE THREAD

**Issue by olivermonberg** [Misioslav/expressvpn#13]
Hi!

When I set the network_mode to the expressvpn service on a clean ubuntu:latest, I do not get the DNS from the expressvpn container but the DNS from my host. Everything works perfectly within the expressvpn container. But I can't resolve anything in ubuntu container, when I cat /etc/resolv.conf I can confirm that the host DNS is being used.

Do you have any idea why this is so?

**Comment by Misioslav** [comment]
Hey!

Can you paste your docker-compose file (or another setup you use)?

**Comment by olivermonberg** [comment]
Sure, I am running just a simple setup. Everything is ok in the log. Expressvpn status is ok and connected. If I bash within the expressvpn container it uses the VPN just as expected. But I cant resolve anything from within the ubuntu container.

docker-compose.yml:

version: "3.8"

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    restart: unless-stopped
    tty: true
    network_mode: service:expressvpn
    depends_on:
      - expressvpn

  expressvpn:
    image: misioslav/expressvpn:3.18.1.0
    container_name: expressvpn
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - CODE=*****
      - SERVER=smart
      - PROTOCOL=auto
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true

**Comment by Misioslav** [comment]
In my case, a similar situation occurs when the container that should send traffic through expressvpn starts before expressvpn actually connects to the servers.

In such a case, I restart the container (not expressvpn one) and it usually works after that.
It is because expressvpn container after connecting to the VPN server changes DNS entries in resolv.conf and other containers (dependent on expressvpn) need to adjust.

I think it could be automated with the use of `wait-for-it` [scripts](https://docs.docker.com/compose/startup-order/).

If that won't work you can also try to set up a custom network for expressvpn container to separate its traffic from the host.

**Comment by olivermonberg** [comment]
Seems right. It still does not work. The resolve.conf has changed in the ubuntu container after a restart though, but it is now containing this:
```
nameserver 127.0.0.11
options ndots:0
```
Where I would expect the same content as in the expressvpn containers resolve.conf:
```
# Generated by expressvpn
search expressvpn
nameserver 10.35.0.1
```

**Comment by Misioslav** [comment]
Actually, in my containers, I also have such entries in resolv.conf and it works. The traffic goes through expressvpn.

Can you try to add to your compose for ubuntu the following?

```
    dns_search:
      - expressvpn
```

**Comment by Misioslav** [comment]
my example entry

```
  exampleService:
    image: maintainer/image
    network_mode: service:expressvpn
    dns_search:
      - expressvpn
    depends_on:
      - expressvpn
    container_name: container
    restart: unless-stopped
    environment:
      - env=env
    volumes:
      - volumes=volumes
 ```

```
  expressvpn:
    image: misioslav/expressvpn:latest
    networks:
      custom_network:
        ipv4_address: ip
    container_name: expressvpn
    restart: unless-stopped
    environment:
      - CODE=${ACTIVATION_CODE}
      - SERVER=smart
      - DDNS=${DDNSDOMAIN}
      - BEARER=${BEARER}
      - HEALTHCHECK=${HEALTHCHECK_EXPRESSVPN}
      - NETWORK=off
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
```

**Comment by olivermonberg** [comment]
Sure. It is still the same.
I will try with the custom network.  Do I need something specific as the subnet?

**Comment by Misioslav** [comment]
For me the `custom_network` is set up as follows:

```
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.1.168.0/24
 ```

**Comment by olivermonberg** [comment]
It still behaves the same.

```
version: "3.8"

services:
  ubuntu:
    image: arm64v8/ubuntu
    container_name: ubuntu
    restart: unless-stopped
    tty: true
    network_mode: service:expressvpn
    dns_search:
      - expressvpn
    depends_on:
      - expressvpn

  expressvpn:
    image: misioslav/expressvpn:3.18.1.0-armhf
    container_name: expressvpn
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      custom_network:
        ipv4_address: 10.1.168.10
    environment:
      - CODE=EDADQPUHHMUJRI26T5QXCNH
      - SERVER=smart
      - PROTOCOL=auto
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.1.168.0/24
```

**Comment by olivermonberg** [comment]
I have tried both on amd64 and arm.

**Comment by Misioslav** [comment]
Tbh, it is weird, Ive just added ubuntu (amd64/ubuntu) to my set up with the following setting:

```
  ubuntu:
    image: amd64/ubuntu
    container_name: ubuntu
    restart: unless-stopped
    tty: true
    network_mode: service:expressvpn
    dns_search:
      - expressvpn
    depends_on:
      - expressvpn
 ```
and it works, `curl ipinfo.io` shows correct expressvpn's ip and I can ping/curl other domains as well.
