### ISSUE TITLE
Sometimes activation fails

### ISSUE THREAD

**Issue by hwamil** [Misioslav/expressvpn#23]
There are times when the container spins up the activation fails and all connections through the container are exposed.

I only noticed when I checked logs on portainer that sometimes when the system reboots or the container is manually restarted.

Is there a way to make the activation persist?

**Comment by hwamil** [comment]
![image](https://user-images.githubusercontent.com/25888359/222490010-235788cc-6199-433a-85ed-15981a35ab73.png)

**Comment by hwamil** [comment]
So binding and persisting `/var/lib/expressvpn` appears to make the activation survive through restarts.
Fingers crossed on this solving my problem.

**Comment by hwamil** [comment]
> So binding and persisting `/var/lib/expressvpn` appears to make the activation survive through restarts. Fingers crossed on this solving my problem.

So this was wrong. I didn't know that some stuff persists if you only restart. Stopping the container and starting it reprompts for activation.

It's my fault I didn't know this, but I read more about what a healthcheck does and seemed like it would solve my issue. So I went ahead and plugged in my DDNS... but it got even more confusing for me.

One session that failed to activate was returning `healthy`. I exec'd into the container to `expressvpn status` and it definitely returned `Not activated`.

So one of two things from my view:
- Healthcheck is not working as it should
- It was actually activated and using the VPN but only appears to be unactivated

Most importantly though, I feel like there should be a failsafe so that if evpn can't activate, it should just shutdown or something so that downloaders do not use raw internet.

Sorry for bothering you with all this. I'm running docker on an rpi4b with x64 debian and your evpn repo is the only one that supports arm64.

**Comment by hwamil** [comment]
Okay so I see that in `healthcheck.sh` it has:

```        if [[ -z expressvpnIP ]];
        then
                /expressvpn/activate.sh
        fi```

so I don't really understand why it won't keep running 'activate.sh' until it is activated. It must not be because evpn is passing the health check, right? But how can it pass the health check if it is not activated in the first place?

**Comment by hwamil** [comment]
![image](https://user-images.githubusercontent.com/25888359/224218789-9ea6b4c1-6e3a-41df-8380-117f7d406af9.png)

**Comment by Misioslav** [comment]
Hey,

What are your docker compose settings? I'm asking because if healthcheck fails it should after 3 failed attempts restart the whole container and try again, but for that you might need in compose `restart: always`.


> Okay so I see that in `healthcheck.sh` it has:
> 
> ```
>         if [[ -z expressvpnIP ]];
>         then
>                 /expressvpn/activate.sh
>         fi
> ```
> 
> so I don't really understand why it won't keep running 'activate.sh' until it is activated. It must not be because evpn is passing the health check, right? But how can it pass the health check if it is not activated in the first place?

`healthcheck.sh` does not have such code in it, at least not in my version. Currently, I do not account for failed activation which might be a mistake and `healthcheck.sh` should additionally try to activate expressvpn when IPs of host machine and expressvpn's are equal.

> ![image](https://user-images.githubusercontent.com/25888359/224218789-9ea6b4c1-6e3a-41df-8380-117f7d406af9.png)
> 
> allowing dns server traffic in iptables: 192.168.1.1
> 
> allowing dns server traffic in iptables: 192.168.1.254
> 
> allowing dns server traffic in iptables: 8.8.8.8
> 

I personally don't use `WHITELIST_DNS` config. Did you try without setting it up?

You can also try this version of `healthcheck.sh` but I did not test it yet. 

```
if [[ ! -z $DDNS ]];
then
	checkIP=$(getent hosts $DDNS | awk '{ print $1 }')
else
	checkIP=$IP
fi

if [[ ! -z $checkIP ]];
then
	expressvpnIP=$(curl -s -H "Authorization: Bearer $BEARER" 'ipinfo.io' | jq --raw-output '.ip')
	if [[ $checkIP = $expressvpnIP || ! $expressvpnIP ]];
	then
		if [[ ! -z $HEALTHCHECK ]];
		then
			curl https://hc-ping.com/$HEALTHCHECK/fail
			expressvpn disconnect
			bash /expressvpn/activate.sh
			expressvpn connect $SERVER
			exit 1
		else
			expressvpn disconnect
			bash /expressvpn/activate.sh
			expressvpn connect $SERVER
			exit 1
		fi
	else
		if [[ ! -z $HEALTHCHECK ]];
		then
			curl https://hc-ping.com/$HEALTHCHECK
			exit 0
		else
			exit 0
		fi
	fi
else
	exit 0
fi
```

**Comment by hwamil** [comment]
> What are your docker compose settings? I'm asking because if healthcheck fails it should after 3 failed attempts restart the whole container and try again, but for that you might need in compose restart: always.

```
  expressvpn:
    image: misioslav/expressvpn:latest-arm64
    container_name: expressvpn
    environment:
      - DDNS=myddns
      - CODE=${CODE}
      - SERVER=usny
      - WHITELIST_DNS=192.168.1.1,192.168.1.254,8.8.8.8
      - PROTOCOL=lightway_udp
      - TZ = ${TZ}
    user: 0:0
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      # ports of other containers that use the vpn (to access them locally)
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

    networks:
      macvlan:
        ipv4_address: 192.168.1.250
```

I do have `restart` as `unless-stopped` so I will change it to `always` - thanks!

> healthcheck.sh does not have such code in it, at least not in my version.

Oh, okay. The container didn't have any text editor so I download the `files` folder from the master branch but it must be from polkaned's repo?

> I personally don't use WHITELIST_DNS config. Did you try without setting it up?
>
> You can also try this version of healthcheck.sh but I did not test it yet.

I filled out the DDNS and WHITELIST_DNS params at the same time so I didn't try without it. I will get rid of it and see how it goes.

As for using another script in the container, I tried to bind `/expressvpn/` folder a host directory but Portainer kept throwing an error along the lines of `You have to wait until the container is running`.
