### ISSUE TITLE
"please activate your account"

### ISSUE THREAD

**Issue by gerberanub** [Misioslav/expressvpn#31]
root@3da5b1035cc0:/# expressvpn connect
Connecting to Smart Location...
Connecting to Japan - Shibuya...
Unable to connect to Japan - Shibuya

   - Check your internet connection or try a different location.
   - Internet traffic is blocked to protect your privacy.
   - To retry the connection, type 'expressvpn connect'
   - To disconnect from the VPN and unblock internet traffic, type 'expressvpn disconnect'
root@3da5b1035cc0:/# expressvpn diagnostics
Client Version: 0.0.1default
Client Shared Version: v23.21.0
OS Name: linux
OS Version: Debian GNU/Linux 11
Internal diagnostics data:
D01: 448, OK
D02: 447, OK
D03: 438
D04: 438, OK
D05: 438, OK
D06: 438
D07: 438, OK
D08: 438, OK
D09: 86707912
D10: 438, OK
D11: 438, OK
D12: N, N
D13: www.2spb2qq8pnqmv.net/api
D14: Japan - Shibuya
D15: auto
D17: 438, OK
D18: 0
Network Lock:         enabled, allow access to local devices
DNS leak protection:  enabled
IPv6 leak protection: enabled
Selected location:    Japan - Shibuya (Smart Location)

==============================================

Connecting to Japan - Shibuya, ip: 24.123.193.169, protocol: lightway_udp

Client Version: 0.0.1default
Client Shared Version: v23.21.0
OS Name: linux
OS Version: Debian GNU/Linux 11
Internal diagnostics data:
D01: 432, OK
D02: 431, OK
D03: 422
D04: 422, OK
D05: 422, OK
D06: 422
D07: 422, OK
D08: 422, OK
D09: 86707896
D10: 422, OK
D11: 422, OK
D12: N, N
D13: www.2spb2qq8pnqmv.net/api
D14: Japan - Shibuya
D15: auto
D17: 422, OK
D18: 0

can't connect please help me

**Comment by Misioslav** [comment]
Hi, what is the exact issue you are facing? I understand you can't connect but it might be caused by a couple of things. The title would suggest you need to have your account activated for expressvpn. Did you already purchase your license key? If you did, did you set it up as env var for your docker configuration?
What machine are you using? Is it Synology, QNAP or maybe a custom build?

**Comment by baszondag** [comment]
Hi, 
im experiencing the same issue. 
i cannot connect to to smart location and im using a Asustor NAS 

The diagnostics give the same output, but still cannot connect the VPN

**Comment by Misioslav** [comment]
Please, post your configuration of your docker or compose file

**Comment by baszondag** [comment]
here is my compose

  expressvpn:
    container_name: expressvpn
    image: misioslav/expressvpn:latest-bookworm  
    environment:
      - ACTIVATION_CODE=${EXPRESSVPN-CODE}
      - SERVER=${EXPRESSVPN_LOCATION}
      - PREFERRED_PROTOCOL=${EXPRESSVPN_PROTOCOL}
      - LIGHTWAY_CIPHER=${EXPRESSVPN_CIPHER}
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    networks:
      - default

EXPRESSVPN_LOCATION=Austria
EXPRESSVPN_PROTOCOL=lightway_udp
EXPRESSVPN_CIPHER=chacha20

**Comment by Misioslav** [comment]
For my docker the environments you are using are incorrect and should be changed:
`ACTIVATION_CODE` should be `CODE`
`PREFERRED_PROTOCOL` should be `PROTOCOL`
`LIGHTWAY_CIPHER` should be `CIPHER`

but the last two are optional so they won't bear much impact but the CODE env will.  Please, change the name of env for code and try again.

**Comment by Webreaper** [comment]
I'm also seeing this. I checked my activation code, and it's definitely correct. Docker-compose: 
```
 expressvpn:
        image: misioslav/expressvpn:latest
        container_name: expressvpn
        environment:
            - CODE={super-sekret-code}
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun:/dev/net/tun"
        stdin_open: true
        privileged: true
        tty: true
        ports:
            - 8090:8090 
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
            - 9117:9117
            - 9696:9696
        command: /bin/bash
        restart: unless-stopped
```
Any ideas?
