### ISSUE TITLE
if ExpressVPN fails to connect, traffic will be routed through the host network

### ISSUE THREAD

**Issue by benblazak** [Misioslav/expressvpn#43]
Making a separate issue for this after all :)

If ExpressVPN fails to connect, e.g. because an invalid `CODE` was passed, and if healthcheck passes (e.g. because no `IP` or `DDNS` was passed or there happens to be an AAAA record for the given DDNS domain), traffic will be routed through the host network without warning.

The easiest fix would be to change this line

https://github.com/Misioslav/expressvpn/blob/5245f4c4cd7415f3e6c3635272672d0110c9dbac/files/start.sh#L38

to

```bash
expressvpn connect $SERVER || exit
```

If ExpressVPN fails to connect, it should exit non-zero, which with this change would fail the container startup (like we want). If ExpressVPN succeeds, network lock should be active, and we shouldn't have to worry about it after that (hopefully).

For now, I've worked around this by adding a line to the `command` for this container in my `compose.yaml`

```bash
expressvpn status | grep -i '^\S*connected to' || exit
```

This works just as well for now (assuming the output of `expressvpn status` doesn't change too much) and doesn't require any changes to the container.

Full `compose.yaml` for reference, now that i've got it working

```yaml
volumes:
  share:

services:
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      # - /path/to/ddclient/config:/config # TODO

  expressvpn:
    image: misioslav/expressvpn:latest-arm64
    container_name: expressvpn
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      CODE: <expressvpn code>
      DDNS: <ddns domain>
    volumes:
      - share:/share
    tty: true
    stdin_open: true
    command:
      - /bin/bash
      - -c
      - |
        expressvpn status | grep -i '^\S*connected to' || exit
        cp /etc/resolv.conf /share/resolv.conf || exit
        exec bash
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:expressvpn
    depends_on:
      expressvpn:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - share:/share:ro
    #   - /path/to/qbittorrent/appdata:/config # TODO
    #   - /path/to/downloads:/downloads # TODO
    tty: true
    stdin_open: true
    command:
      - /bin/bash
      - -c
      - |
        cp /share/resolv.conf /etc/resolv.conf || exit
        exec bash
```
