### ISSUE TITLE
latest version restart loop

### ISSUE THREAD

**Issue by phynias** [Misioslav/expressvpn#46]
Not sure what is wrong as there are no errors or anything, but I updated to latest version and it starts just fine logs look normal and then it restarts. Infinitely.

I go back to `3.68.0.2` and everything works fine.

**Comment by Misioslav** [comment]
Hi, Im using the latest on my main machine and it seems to works fine, Ive just set it up also on my second machine to observe its behavior but after 15min so far so good.

The latest changes that were introduced are:


```
output=$(service expressvpn restart)
if echo "$output" | grep -q "failed!" > /dev/null
then
    echo "Service expressvpn restart failed!"
    exit 1
fi
```

and

```
output=$(expect -f /expressvpn/activate.exp "$CODE")
if echo "$output" | grep -q "Please activate your account" > /dev/null || echo "$output" | grep -q "Activation failed" > /dev/null
then
    echo "Activation failed!"
    exit 1
fi
```

so basically conditions to mark the container as unhealthy, which were previously not working from what Ive noticed.
Additional change was `expressvpn connect $SERVER || exit` so in case of not connecting to do the same as above. I see I did not add `1` to exit but I do not think it would cause the looping.
I undertand you did not make any changes on your end? Like configuration, compose, etc.?
The changes above may cause looping essentially if the checks fail and restart policy allows it.

**Comment by chillheart** [comment]
I am having the same problem, ever since upgrading past 3.68.0.2. 

Here are a copy of the logs

```
Preferred Protocol is lightway_udp.
LightwayCipher is chacha20.
Send Diagnostics is disabled.
Advanced protection block trackers is enabled.
Network Lock Mode is default.
Auto Connect is enabled.
ExpressVPN for Linux v3.74.0.6 is now available.
To update ExpressVPN, run sudo apt update && sudo apt install --only-upgrade expressvpn
If you encounter an issue, download the app manually at https://www.vlycgtx.com/latest#linux
Connecting to Smart Location...

Connecting to USA - Albuquerque...
Connecting to USA - Albuquerque...	1.0%
Connecting to USA - Albuquerque...	15.0%
Connecting to USA - Albuquerque...	37.5%
Connecting to USA - Albuquerque...	75.0%
Connecting to USA - Albuquerque...	85.0%
Connecting to USA - Albuquerque...	100.0%
Connected to USA - Albuquerque
```
I have it defined as part of a docker compose file to route all my connections through.

```
expressvpn:
    devices:
     - "/dev/net/tun"
    image: misioslav/expressvpn:3.73.0.0
    ports:
      - 80:80
    privileged: true
    environment:
      CODE: <redacted>
      DDNS: <redacted>
      BEAERER: <redacted>
      HEALTHCHECK: <redacted>
      SERVER: SMART
    labels:
      failure_notify: true
      failure_notify_email: "<redacted>"
    restart: always
```
